// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7zXWV1m40lbyrLpLyisQ43mnN2ztLlKc',
    appId: '1:650846877028:web:eefb52a7de59550cd23671',
    messagingSenderId: '650846877028',
    projectId: 'test-5c129',
    authDomain: 'test-5c129.firebaseapp.com',
    storageBucket: 'test-5c129.appspot.com',
    measurementId: 'G-P4N6VZGWNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtmcJgkXQkFOh-6hHXZ2yMKFA25K95aj0',
    appId: '1:650846877028:android:ec19be53eede6ae7d23671',
    messagingSenderId: '650846877028',
    projectId: 'test-5c129',
    storageBucket: 'test-5c129.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_hmu7f4uEy8chZWB-MiL3giVoOiQ1jVI',
    appId: '1:650846877028:ios:7a5792bca056313ed23671',
    messagingSenderId: '650846877028',
    projectId: 'test-5c129',
    storageBucket: 'test-5c129.appspot.com',
    iosBundleId: 'com.example.netflexProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_hmu7f4uEy8chZWB-MiL3giVoOiQ1jVI',
    appId: '1:650846877028:ios:7a5792bca056313ed23671',
    messagingSenderId: '650846877028',
    projectId: 'test-5c129',
    storageBucket: 'test-5c129.appspot.com',
    iosBundleId: 'com.example.netflexProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7zXWV1m40lbyrLpLyisQ43mnN2ztLlKc',
    appId: '1:650846877028:web:8148f97512a37f3bd23671',
    messagingSenderId: '650846877028',
    projectId: 'test-5c129',
    authDomain: 'test-5c129.firebaseapp.com',
    storageBucket: 'test-5c129.appspot.com',
    measurementId: 'G-6L4G112GR8',
  );
}
